"""
generalized_pipe_dreams.py

Generalized / not-necessarily-reduced pipe dreams.

Representation:
---------------
A pipe dream is a frozenset of crossed cells.

Example:
    D = frozenset({(0, 0), (0, 1), (0, 3)})

The cell (r, c) means row r, column c has a cross.

Rows and columns are 0-indexed.

For permutations in S_n, the staircase grid is:

    r >= 0,
    c >= 0,
    r + c <= n - 2.

A cross at cell (r, c) contributes the simple transposition

    s_{r+c+1}.

"""

from __future__ import annotations

from collections import deque
from itertools import combinations
from typing import FrozenSet, Iterable, Iterator, List, Optional, Sequence, Set, Tuple


Cell = Tuple[int, int]
PipeDream = FrozenSet[Cell]
Permutation = Tuple[int, ...]


# ---------------------------------------------------------------------
# Permutation utilities
# ---------------------------------------------------------------------

def validate_permutation(w: Sequence[int]) -> None:
    """
    Check that w is a permutation of 1, 2, ..., n.
    """
    n = len(w)

    if n == 0:
        raise ValueError("The permutation cannot be empty.")

    if sorted(w) != list(range(1, n + 1)):
        raise ValueError(f"{list(w)} is not a valid permutation of 1, 2, ..., {n}.")


def inversion_length(p: Sequence[int]) -> int:
    """
    Return the number of inversions of a permutation.
    """
    return sum(
        1
        for i in range(len(p))
        for j in range(i + 1, len(p))
        if p[i] > p[j]
    )


def apply_simple_transposition(p: Sequence[int], k: int) -> Permutation:
    """
    Apply s_k to p.

    In one-line notation, this swaps positions k and k+1.
    """
    n = len(p)

    if not (1 <= k < n):
        raise ValueError(f"s_{k} is not valid for a permutation in S_{n}.")

    q = list(p)
    q[k - 1], q[k] = q[k], q[k - 1]

    return tuple(q)


# ---------------------------------------------------------------------
# Cell / grid utilities
# ---------------------------------------------------------------------

def valid_cell(cell: Cell, n: int) -> bool:
    """
    Return True if cell lies in the S_n staircase.
    """
    r, c = cell
    return 0 <= r < n - 1 and 0 <= c < n - 1 - r


def staircase_cells(n: int) -> List[Cell]:
    """
    Return all cells in the S_n staircase.
    """
    if n <= 0:
        raise ValueError("n must be positive.")

    cells: List[Cell] = []

    for r in range(n - 1):
        for c in range(n - 1 - r):
            cells.append((r, c))

    return cells


def check_pipe_dream_cells(D: PipeDream, n: int) -> None:
    """
    Raise an error if D contains cells outside the staircase.
    """
    bad = [cell for cell in D if not valid_cell(cell, n)]

    if bad:
        raise ValueError(f"Pipe dream contains invalid cells for S_{n}: {bad}")


def cell_generator(cell: Cell) -> int:
    """
    A cross at cell (r, c) contributes s_{r+c+1}.
    """
    r, c = cell
    return r + c + 1


def reading_cells(D: PipeDream, n: int) -> List[Cell]:
    """
    Return cells with crosses in reading order.

    Rows are read top to bottom.
    Each row is read right to left.
    """
    check_pipe_dream_cells(D, n)

    result: List[Cell] = []

    for r in range(n - 1):
        for c in range(n - 2 - r, -1, -1):
            if (r, c) in D:
                result.append((r, c))

    return result


def reading_word(D: PipeDream, n: int) -> List[int]:
    """
    Return the reading word of the pipe dream.

    Example output:
        [4, 2, 1]
    means:
        s_4 s_2 s_1.
    """
    return [cell_generator(cell) for cell in reading_cells(D, n)]


# ---------------------------------------------------------------------
# pipe permutation
# ---------------------------------------------------------------------

def pipe_permutation(D: PipeDream, n: int) -> Permutation:
    """
    Compute the ordinary permutation generated by D.
    """
    check_pipe_dream_cells(D, n)

    p: Permutation = tuple(range(1, n + 1))

    for k in reading_word(D, n):
        p = apply_simple_transposition(p, k)

    return p


def generates_permutation(D: PipeDream, w: Sequence[int]) -> bool:
    """
    Return True if D generates w.
    """
    validate_permutation(w)
    return pipe_permutation(D, len(w)) == tuple(w)


def is_reduced_pipe_dream(D: PipeDream, n: int) -> bool:
    """
    Return True if D is reduced.

    A pipe dream is reduced if the number of crosses equals the
    inversion length of its generated permutation.
    """
    perm = pipe_permutation(D, n)
    return len(D) == inversion_length(perm)


def is_nonreduced_pipe_dream(D: PipeDream, n: int) -> bool:
    """
    Return True if D is not reduced.
    """
    return not is_reduced_pipe_dream(D, n)


# ---------------------------------------------------------------------
# Top pipe dream
# ---------------------------------------------------------------------

def top_pipe_dream(w: Sequence[int]) -> PipeDream:
    """
    Construct the usual reduced top pipe dream for w.

    For each value j, count how many larger values appear before j in w.
    Then place that many crosses at the top of column j.

    Internally columns are 0-indexed, so value j uses column j - 1.
    """
    validate_permutation(w)

    n = len(w)
    pos = {value: i for i, value in enumerate(w)}
    crosses: Set[Cell] = set()

    for value in range(1, n + 1):
        position = pos[value]
        count = sum(1 for i in range(position) if w[i] > value)

        c = value - 1

        for r in range(count):
            cell = (r, c)

            if valid_cell(cell, n):
                crosses.add(cell)

    return frozenset(crosses)


# ---------------------------------------------------------------------
# Rectangle helpers for generalized chute moves
# ---------------------------------------------------------------------

def rectangle_cells(r1: int, r2: int, c1: int, c2: int) -> List[Cell]:
    """
    Return all cells in the rectangle [r1, r2] x [c1, c2].
    """
    return [
        (r, c)
        for r in range(r1, r2 + 1)
        for c in range(c1, c2 + 1)
    ]


def rectangle_inside_staircase(r1: int, r2: int, c1: int, c2: int, n: int) -> bool:
    """
    Return True if the whole rectangle lies inside the staircase.
    """
    for r in range(r1, r2 + 1):
        for c in range(c1, c2 + 1):
            if not valid_cell((r, c), n):
                return False

    return True


# ---------------------------------------------------------------------
# Generalized chute moves
# ---------------------------------------------------------------------

def generalized_chute_neighbors(
    D: PipeDream,
    n: int,
    *,
    verify_permutation: bool = True,
) -> Iterator[PipeDream]:
    """
    Generate generalized chute move neighbors.

    We choose a rectangle with corners:

        NW = (r1, c1)
        NE = (r1, c2)
        SW = (r2, c1)
        SE = (r2, c2)

    with r1 < r2 and c1 < c2.

    The move sends a cross from NE to SW.

    More precisely, before the move:

        - NW is empty
        - SW is empty
        - NE is crossed
        - all cells in the rectangle except NW, SW, and SE are crossed
        - SE may be empty or crossed

    Then NE is changed to empty and SW is changed to crossed.

    If verify_permutation is True, this function only yields moves that
    preserve the ordinary pipe permutation.
    """
    check_pipe_dream_cells(D, n)

    Dset = set(D)
    base_perm = pipe_permutation(D, n) if verify_permutation else None

    for r1 in range(n - 1):
        for r2 in range(r1 + 1, n - 1):
            for c1 in range(n - 1):
                for c2 in range(c1 + 1, n - 1):
                    if not rectangle_inside_staircase(r1, r2, c1, c2, n):
                        continue

                    NW = (r1, c1)
                    NE = (r1, c2)
                    SW = (r2, c1)
                    SE = (r2, c2)

                    if NW in Dset:
                        continue

                    if SW in Dset:
                        continue

                    if NE not in Dset:
                        continue

                    ok = True

                    for cell in rectangle_cells(r1, r2, c1, c2):
                        if cell in {NW, SW, SE}:
                            continue

                        if cell not in Dset:
                            ok = False
                            break

                    if not ok:
                        continue

                    newD = set(Dset)
                    newD.remove(NE)
                    newD.add(SW)

                    E = frozenset(newD)

                    if verify_permutation and pipe_permutation(E, n) != base_perm:
                        continue

                    yield E


def inverse_generalized_chute_neighbors(
    D: PipeDream,
    n: int,
    *,
    verify_permutation: bool = True,
) -> Iterator[PipeDream]:
    """
    Generate inverse generalized chute move neighbors.

    This reverses generalized_chute_neighbors.

    It sends a cross from SW back to NE.
    """
    check_pipe_dream_cells(D, n)

    Dset = set(D)
    base_perm = pipe_permutation(D, n) if verify_permutation else None

    for r1 in range(n - 1):
        for r2 in range(r1 + 1, n - 1):
            for c1 in range(n - 1):
                for c2 in range(c1 + 1, n - 1):
                    if not rectangle_inside_staircase(r1, r2, c1, c2, n):
                        continue

                    NW = (r1, c1)
                    NE = (r1, c2)
                    SW = (r2, c1)
                    SE = (r2, c2)

                    if NW in Dset:
                        continue

                    if NE in Dset:
                        continue

                    if SW not in Dset:
                        continue

                    ok = True

                    for cell in rectangle_cells(r1, r2, c1, c2):
                        if cell in {NW, NE, SE}:
                            continue

                        if cell not in Dset:
                            ok = False
                            break

                    if not ok:
                        continue

                    newD = set(Dset)
                    newD.remove(SW)
                    newD.add(NE)

                    E = frozenset(newD)

                    if verify_permutation and pipe_permutation(E, n) != base_perm:
                        continue

                    yield E


# ---------------------------------------------------------------------
# Double-cross flips
# ---------------------------------------------------------------------

def double_cross_flip_neighbors(
    D: PipeDream,
    n: int,
    *,
    verify_permutation: bool = True,
) -> Iterator[PipeDream]:
    """
    Generate double-cross flip neighbors.

    A double-cross flip changes 2 tiles at once.

    It allows:

        two elbows  -> two crosses

    and the reverse:

        two crosses -> two elbows

    This implementation is computational:
    it tries every pair of cells and keeps only the pairs that preserve
    the ordinary pipe permutation.

    That means it is safe for correctness, although not the fastest
    possible implementation.
    """
    check_pipe_dream_cells(D, n)

    Dset = set(D)
    cells = staircase_cells(n)
    base_perm = pipe_permutation(D, n) if verify_permutation else None

    for cell1, cell2 in combinations(cells, 2):
        cell1_crossed = cell1 in Dset
        cell2_crossed = cell2 in Dset

        both_empty = not cell1_crossed and not cell2_crossed
        both_crossed = cell1_crossed and cell2_crossed

        # A double-cross flip should not toggle one crossed cell
        # and one empty cell. It must change the cross count by +/- 2.
        if not (both_empty or both_crossed):
            continue

        newD = set(Dset)

        if both_empty:
            newD.add(cell1)
            newD.add(cell2)

        elif both_crossed:
            newD.remove(cell1)
            newD.remove(cell2)

        E = frozenset(newD)

        if verify_permutation and pipe_permutation(E, n) != base_perm:
            continue

        yield E


# ---------------------------------------------------------------------
# Move graph
# ---------------------------------------------------------------------

def neighbors(
    D: PipeDream,
    n: int,
    *,
    include_inverse_chute: bool = True,
    include_double_cross_flips: bool = True,
    verify_permutation: bool = True,
) -> Iterator[PipeDream]:
    """
    Generate all selected neighbors of D.

    By default this includes:

        - generalized chute moves
        - inverse generalized chute moves
        - double-cross flips
    """
    yield from generalized_chute_neighbors(
        D,
        n,
        verify_permutation=verify_permutation,
    )

    if include_inverse_chute:
        yield from inverse_generalized_chute_neighbors(
            D,
            n,
            verify_permutation=verify_permutation,
        )

    if include_double_cross_flips:
        yield from double_cross_flip_neighbors(
            D,
            n,
            verify_permutation=verify_permutation,
        )


# ---------------------------------------------------------------------
# Enumeration
# ---------------------------------------------------------------------

def sorted_pipe_dreams(dreams: Iterable[PipeDream]) -> List[PipeDream]:
    """
    Sort pipe dreams first by number of crosses, then by their cells.
    """
    return sorted(
        dreams,
        key=lambda D: (len(D), sorted(D)),
    )


def all_generalized_pipe_dreams_by_moves(
    w: Sequence[int],
    *,
    start: Optional[PipeDream] = None,
    max_states: Optional[int] = None,
    include_inverse_chute: bool = True,
    include_double_cross_flips: bool = True,
    verify_permutation: bool = True,
) -> List[PipeDream]:
    """
    Enumerate generalized pipe dreams for w by BFS from the top pipe dream.

    The allowed moves are:

        - generalized chute moves
        - inverse generalized chute moves
        - double-cross flips

    The invariant is the pipe permutation.

    Parameters:
    -----------
    w:
        Target permutation.

    start:
        Optional starting pipe dream.
        If None, use top_pipe_dream(w).

    max_states:
        Optional safety cap. If the BFS reaches this many states,
        it stops early and returns what it has found.

    Returns:
    --------
    A sorted list of reachable pipe dreams generating w.
    """
    validate_permutation(w)

    n = len(w)
    target = tuple(w)

    if start is None:
        start = top_pipe_dream(w)

    check_pipe_dream_cells(start, n)

    if pipe_permutation(start, n) != target:
        raise ValueError(
            "The starting pipe dream does not generate the target permutation "
            "under the ordinary product."
        )

    seen: Set[PipeDream] = {start}
    queue = deque([start])

    while queue:
        D = queue.popleft()

        for E in neighbors(
            D,
            n,
            include_inverse_chute=include_inverse_chute,
            include_double_cross_flips=include_double_cross_flips,
            verify_permutation=verify_permutation,
        ):
            if pipe_permutation(E, n) != target:
                continue

            if E in seen:
                continue

            seen.add(E)
            queue.append(E)

            if max_states is not None and len(seen) >= max_states:
                return sorted_pipe_dreams(seen)

    return sorted_pipe_dreams(seen)


def all_pipe_dreams_by_filter(w: Sequence[int]) -> List[PipeDream]:
    """
    Brute-force all subsets of the staircase whose ordinary product is w.

    Warning:
    --------
    This grows very quickly.

        S_5:  2^10 = 1,024 states
        S_6:  2^15 = 32,768 states
        S_7:  2^21 = 2,097,152 states
    """
    validate_permutation(w)

    n = len(w)
    target = tuple(w)
    cells = staircase_cells(n)
    result: List[PipeDream] = []

    for mask in range(1 << len(cells)):
        D = frozenset(
            cells[i]
            for i in range(len(cells))
            if (mask >> i) & 1
        )

        if pipe_permutation(D, n) == target:
            result.append(D)

    return sorted_pipe_dreams(result)


def reduced_pipe_dreams(w: Sequence[int]) -> List[PipeDream]:
    """
    Return reachable reduced pipe dreams for w.
    """
    n = len(w)
    dreams = all_generalized_pipe_dreams_by_moves(w)

    return [
        D for D in dreams
        if is_reduced_pipe_dream(D, n)
    ]


def nonreduced_pipe_dreams(w: Sequence[int]) -> List[PipeDream]:
    """
    Return reachable non-reduced pipe dreams for w.
    """
    n = len(w)
    dreams = all_generalized_pipe_dreams_by_moves(w)

    return [
        D for D in dreams
        if not is_reduced_pipe_dream(D, n)
    ]


def compare_moves_to_bruteforce(w: Sequence[int]) -> Tuple[bool, Set[PipeDream], Set[PipeDream]]:
    """
    Compare move-based enumeration with brute-force enumeration.

    Returns:
        (matches, missing, extra)

    missing = brute force states not reached by moves
    extra   = move-generated states not found by brute force

    """
    brute = set(all_pipe_dreams_by_filter(w))
    moves = set(all_generalized_pipe_dreams_by_moves(w))

    return brute == moves, brute - moves, moves - brute


# ---------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------

def to_matrix(D: PipeDream, n: int, *, square: bool = True) -> List[List[int]]:
    """
    Convert a pipe dream to a matrix of 0s and 1s.

    If square=True, return an n by n matrix.

    If square=False, return only the staircase rows.
    """
    check_pipe_dream_cells(D, n)

    if square:
        return [
            [1 if (r, c) in D else 0 for c in range(n)]
            for r in range(n)
        ]

    return [
        [1 if (r, c) in D else 0 for c in range(n - 1 - r)]
        for r in range(n - 1)
    ]


def pipe_dream_to_string(
    D: PipeDream,
    n: int,
    *,
    cross_symbol: str = "+",
    empty_symbol: str = ".",
) -> str:
    """
    Return a printable staircase representation.
    """
    check_pipe_dream_cells(D, n)

    rows: List[str] = []

    for r in range(n - 1):
        pieces: List[str] = []

        for c in range(n - 1 - r):
            cell = (r, c)

            if cell in D:
                pieces.append(cross_symbol)
            else:
                pieces.append(empty_symbol)

        rows.append(" ".join(pieces))

    return "\n".join(rows)


def print_pipe_dream(
    D: PipeDream,
    n: int,
    *,
    show_word: bool = True,
    show_perm: bool = True,
    show_cross_count: bool = True,
    show_reduced: bool = True,
) -> None:
    """
    Print a pipe dream and optional data.
    """
    print(pipe_dream_to_string(D, n))

    if show_word:
        print("word:", reading_word(D, n))

    if show_perm:
        print("ordinary permutation:", pipe_permutation(D, n))

    if show_cross_count:
        print("crosses:", len(D))

    if show_reduced:
        print("reduced:", is_reduced_pipe_dream(D, n))


def monomial_exponents(D: PipeDream, n: int) -> Tuple[int, ...]:
    """
    Return the exponent vector of the pipe dream monomial.

    Each cross in row r contributes one factor of x_{r+1}.
    """
    check_pipe_dream_cells(D, n)

    return tuple(
        sum(1 for c in range(n) if (r, c) in D)
        for r in range(n)
    )


# ---------------------------------------------------------------------
# Input parser and demo
# ---------------------------------------------------------------------

def parse_permutation(text: str) -> List[int]:
    """
    Parse a permutation from user input.

    Accepts:
        31254
        3 1 2 5 4
        3,1,2,5,4

    Note:
        Compact input like 31254 only works cleanly for n <= 9.
        For n >= 10, use spaces or commas.
    """
    text = text.strip()

    if not text:
        raise ValueError("Empty permutation input.")

    if "," in text:
        return [int(piece.strip()) for piece in text.split(",") if piece.strip()]

    if " " in text:
        return [int(piece.strip()) for piece in text.split() if piece.strip()]

    return [int(ch) for ch in text]

